language: python
sudo: false

matrix:
  include:
    - env: TOXENV=py27-twisted12
      python: "2.7"
    - env: TOXENV=py27-twisted13
      python: "2.7"
    - env: TOXENV=py27-twisted14
      python: "2.7"
    - env: TOXENV=py27-twisted15
      python: "2.7"
    - env: TOXENV=py27-twisted16
      python: "2.7"
    - env: TOXENV=py35-twisted16
      python: "3.5"
    - env: TOXENV=pypy-twisted12
      python: "pypy"
    - env: TOXENV=pypy-twisted13
      python: "pypy"
    - env: TOXENV=pypy-twisted14
      python: "pypy"
    - env: TOXENV=pypy-twisted15
      python: "pypy"
    - env: TOXENV=pypy-twisted16
      python: "pypy"
    - env: TOXENV=pypy3-twisted16
      python: "pypy3"
  allow_failures:
    - env: TOXENV=pypy3-twisted16

install:
    - pip install tox coveralls pep8 pyflakes

script: make lint && tox

after_success: coveralls
